import LocalizedStrings from 'react-localization';

const strings = new LocalizedStrings({
    es: {
        openYourSLANow1: 'Crea tu SLA',
        openYourSLANow2: 'ahora',
        openYourSLANow3: 'en <strong>BlockChain</strong>',
        iWantIt: '¡Lo quiero!',

        // Form information
        formInformationDNI: 'DNI',
        formInformationDNIPlaceHolder: 'Introduce número DNI',
        formInformationDNIError: 'Por favor, indica un DNI válido.',
        formInformationFirstName: 'Nombre',
        formInformationFirstNamePlaceHolder: 'Introduce nombre',
        formInformationFirstNameError: 'Por favor, indica un nombre válido.',
        formInformationLastName: 'Apellidos',
        formInformationLastNamePlaceHolder: 'Introduce apellidos',
        formInformationLastNameError: 'Por favor, indica unos apellidos válidos',
        formInformationCountryChoose: 'Selecciona país ...',
        formInformationGenderChoose: 'Selecciona género ...',
        formInformationGenderMale: 'Masculino',
        formInformationGenderFemale: 'Femenino',
        formInformationGenderOther: 'Otro',
        formInformationCity: 'Ciudad',
        formInformationCityPlaceHolder: 'Introduce ciudad',
        formInformationProvince: 'Provincia',
        formInformationProvincePlaceHolder: 'Introduce provincia',
        formInformationCompanyName: 'Nombre empresa',
        formInformationCompanyNamePlaceHolder: 'Introduce empresa',
        formInformationCompanyNameError: 'Por favor, introduce una empresa válida.',
        formInformationCompanyDirection: 'Dirección empresa',
        formInformationCompanyDirectionPlaceHolder: 'Introduce dirección de empresa',
        formInformationCompanyDirectionError: 'Por favor, introduce una dirección de empresa válida.',
        formInformationCompanyNumber: 'Número fiscal empresa',
        formInformationCompanyNumberPlaceHolder: 'Introduce el número fiscal',
        formInformationCompanyNumberError: 'Por favor, introduce un número fiscal válido.',

        formClientInformation: 'Información del cliente',
        formServiceProviderInformation: 'Información del proveedor del servicio',

        // Form SLA specification
        formSLASpecification: 'Detalles SLA',
        formSLASpecificationDuration: 'Duración SLA',
        formSLASpecificationClientCoveredServices: 'Cobertura de servicios',
        formSLASpecificationClientContact: 'Contacto cliente',
        formSLASpecificationServiceProviderContact: 'Contacto proveedor servicios',
        formSLASpecificationContactFirstName: 'Nombre',
        formSLASpecificationContactFirstNamePlaceHolder: 'Introduce nombre',
        formSLASpecificationContactFirstNameError: 'Por favor, introduce un nombre válido.',
        formSLASpecificationContactLastName: 'Apellidos',
        formSLASpecificationContactLastNamePlaceHolder: 'Introduce apellidos',
        formSLASpecificationContactLastNameError: 'Por favor, introduce unos apellidos válidos.',
        formSLASpecificationContactEmail: 'Correo electrónico',
        formSLASpecificationContactEmailPlaceHolder: 'nombre@ejemplo.com',
        formSLASpecificationContactPhone: 'Número teléfono',
        formSLASpecificationContactPhonePlaceHolder: '+34 666555444',
        formSLASpecificationRelatedFiles: 'Archivos relacionados',
        formSLASpecificationChooseStart: 'Seleccionar inicio ...',
        formSLASpecificationChooseEnd: 'Seleccionar fin ...',
        formSLASpecificationServiceLevel: 'Niveles de servicio',
        formSLASpecificationServiceExclusions: 'Exclusiones de servicio',

        // Form service assurance
        formServiceAssurance: 'Garantía de servicio',
        formServiceAssuranceComplaintProcedure: 'Procedimiento de queja',
        formServiceAssurancePerformPenalty: 'Penalización de rendimiento',
        formServiceAssuranceOperatingSafety: 'Seguridad operacional',
        formServiceAssuranceReport: 'Reporte',
        formServiceAssuranceChoosePeriod: 'Selecciona periodo ...',
        formServiceAssuranceRecipientEmail: 'Correo electrónico para reportes',
        formServiceAssuranceIncidentManager: 'Administracion de incidentes',
        formServiceAssuranceConfidentiality: 'Confidencialidad',
        formServiceAssuranceServiceMonitoring: 'Monitoreo de servicio',
        formServiceAssuranceSelectServiceMonitoring: 'Selecciona periodo ...',
        formServiceAssuranceServiceBilling: 'Facturación de servicios',
        formServiceAssuranceSelectServiceBilling: 'Selecciona periodo ...',
        formServiceAssuranceSelectBillingMethod: 'Selecciona método de facturación ...',

        // Form general
        formLooksGood: '¡Tiene buena pinta!',
        formShareWithAnyoneElse: 'Nunca compartiremos esto con alguien.',
        formFieldsAreMandatory: 'Los campos con * son obligatorios',
        formSubmit: 'Enviar',
    },

    en: {
        openYourSLANow1: 'Open your SLA',
        openYourSLANow2: 'NOW',
        openYourSLANow3: 'in <strong>BlockChain</strong>',
        iWantIt: 'I WANT IT!',

        // Form information
        formInformationDNI: 'DNI',
        formInformationDNIPlaceHolder: 'Enter DNI card number',
        formInformationDNIError: 'Please provide a valid DNI.',
        formInformationFirstName: 'First name',
        formInformationFirstNamePlaceHolder: 'Enter the first name',
        formInformationFirstNameError: 'Please provide a valid first name.',
        formInformationLastName: 'Last name',
        formInformationLastNamePlaceHolder: 'Enter the last name',
        formInformationLastNameError: 'Please provide a valid last name.',
        formInformationCountryChoose: 'Choose country ...',
        formInformationGenderChoose: 'Choose gender ...',
        formInformationGenderMale: 'Male',
        formInformationGenderFemale: 'Female',
        formInformationGenderOther: 'Other',
        formInformationCity: 'City',
        formInformationCityPlaceHolder: 'Enter the city name',
        formInformationProvince: 'Province',
        formInformationProvincePlaceHolder: 'Enter the province name',
        formInformationCompanyName: 'Company name',
        formInformationCompanyNamePlaceHolder: 'Enter the company name',
        formInformationCompanyNameError: 'Please provide a valid company name.',
        formInformationCompanyDirection: 'Company direction',
        formInformationCompanyDirectionPlaceHolder: 'Enter the company direction',
        formInformationCompanyDirectionError: 'Please provide a valid company direction.',
        formInformationCompanyNumber: 'Company fiscal number',
        formInformationCompanyNumberPlaceHolder: 'Enter the fiscal number',
        formInformationCompanyNumberError: 'Please provide a valid fiscal number.',

        formClientInformation: 'Client information',
        formServiceProviderInformation: 'Service Provider Information',

        // Form SLA specification
        formSLASpecification: 'SLA Specification',
        formSLASpecificationDuration: 'SLA duration',
        formSLASpecificationClientCoveredServices: 'Covered services',
        formSLASpecificationClientContact: 'Client contact',
        formSLASpecificationServiceProviderContact: 'Service provider contact',
        formSLASpecificationContactFirstName: 'First name',
        formSLASpecificationContactFirstNamePlaceHolder: 'Enter the first name',
        formSLASpecificationContactFirstNameError: 'Please provide a valid first name.',
        formSLASpecificationContactLastName: 'Last name',
        formSLASpecificationContactLastNamePlaceHolder: 'Enter the last name',
        formSLASpecificationContactLastNameError: 'Please provide a valid last name.',
        formSLASpecificationContactEmail: 'Email address',
        formSLASpecificationContactEmailPlaceHolder: 'name@example.com',
        formSLASpecificationContactPhone: 'Phone number',
        formSLASpecificationContactPhonePlaceHolder: '+34 666555444',
        formSLASpecificationRelatedFiles: 'Related files',
        formSLASpecificationChooseStart: 'Choose start ...',
        formSLASpecificationChooseEnd: 'Choose end ...',
        formSLASpecificationServiceLevel: 'Service levels',
        formSLASpecificationServiceExclusions: 'Service exclusions',

        // Form service assurance
        formServiceAssurance: 'Service Assurance',
        formServiceAssuranceComplaintProcedure: 'Complaint procedure',
        formServiceAssurancePerformPenalty: 'Performance penalty',
        formServiceAssuranceOperatingSafety: 'Operating Safety',
        formServiceAssuranceReport: 'Report',
        formServiceAssuranceChoosePeriod: 'Choose period ...',
        formServiceAssuranceRecipientEmail: 'Report recipient email',
        formServiceAssuranceIncidentManager: 'Incident management',
        formServiceAssuranceConfidentiality: 'Confidentiality',
        formServiceAssuranceServiceMonitoring: 'Service monitoring',
        formServiceAssuranceSelectServiceMonitoring: 'Choose period ...',
        formServiceAssuranceServiceBilling: 'Service Billing',
        formServiceAssuranceSelectServiceBilling: 'Choose period ...',
        formServiceAssuranceSelectBillingMethod: 'Choose billing method',

        // Form general
        formLooksGood: 'Looks good!',
        formShareWithAnyoneElse: 'We\'ll never share this with anyone else.',
        formFieldsAreMandatory: 'Fields with * are mandatory in this form',
        formSubmit: 'Submit',
    }
});

export default strings;
